"""Initial migration

Revision ID: 1ed1cbcc3c56
Revises: 7e89257ba241
Create Date: 2024-08-31 17:30:15.800291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ed1cbcc3c56'
down_revision = '7e89257ba241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
