"""Initial migration

Revision ID: 7e89257ba241
Revises: bc34b4da1655
Create Date: 2024-08-31 16:47:08.103056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e89257ba241'
down_revision = 'bc34b4da1655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
