"""Update schema for products and images

Revision ID: 942f1cc4396d
Revises: 1e8d7d135a19
Create Date: 2024-08-31 13:00:55.884519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942f1cc4396d'
down_revision = '1e8d7d135a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('images_product_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'products', ['serial_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_product_id_fkey', 'images', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
