"""Initial migration

Revision ID: a655b30dbb35
Revises: 
Create Date: 2024-08-30 21:57:56.694815

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a655b30dbb35'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop foreign key constraint before dropping the table
    op.drop_constraint('images_product_id_fkey', 'images', type_='foreignkey')

    # Drop tables
    op.drop_table('products')
    op.drop_table('images')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Recreate tables with their original schema
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='products_pkey')
    )

    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('input_image_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('output_image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='images_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='images_pkey')
    )

    # ### end Alembic commands ###
