"""Update schema for products and images

Revision ID: b8f7627ecdbb
Revises: 942f1cc4396d
Create Date: 2024-08-31 13:06:56.933651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f7627ecdbb'
down_revision = '942f1cc4396d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
