"""empty message

Revision ID: bc34b4da1655
Revises: b8f7627ecdbb
Create Date: 2024-08-31 14:27:27.428279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc34b4da1655'
down_revision = 'b8f7627ecdbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
